#!/usr/bin/env bash

set -e
root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

unset PIP_FIND_LINKS
export PIP_INDEX_URL='http://devpi/pi'
export PIP_TRUSTED_HOST='devpi'

main() {
    cd "$root"

    if [[ $1 ]]; then
        "$@"
        return
    fi

    scl enable python27 "
        /opt/rh/python27/root/usr/bin/virtualenv env ||
        /usr/bin/virtualenv env ||
        virtualenv env

        scl_patch_virtualenv env
    "

    if [[ $one_up_activate ]]; then
        ln -sf "$(basename "$root")/env/bin/activate" ../activate
    else
        ln -sf env/bin/activate activate
    fi

    install_packages
}

install_packages() {
    . env/bin/activate
    upgrade_pip
    pip_install -r requirements.pip
}

upgrade_pip() {
    pip_install -U 'pip==6.1.1'
    pip_install -U 'setuptools==5.4.1'
}

pip_install() {
    pip install -U "$@" 2>&1 |
    grep -v 'DEPRECATION: Failed to find'
}

main "$@"
